GOOGLE_APP_ID: '387041439815-t7f0fs5eik3papnpr99sfgl4sphiqp19.apps.googleusercontent.com'
GOOGLE_APP_SECRET: '2IaxM74a2tj9WfbH3j7KiYfU'

FACEBOOK_APP_ID: '359138667962493'
FACEBOOK_APP_SECRET: 'acd958cf830ea5de6aa396a365d2a955'

TWITTER_APP_ID: 'so23cS4oT6F6bxHEW7K0aHJMV'
TWITTER_APP_SECRET: 'ZrVMWCajhkzPF1CbA6jt2kPdPB0k5NmSnmtgbdbQhRClmbKIxY'